class Autogenerated {
  int? id;
  String? username;
  String? email;
  String? password;
  List<UserTodo>? userTodo;

  Autogenerated(
      {this.id, this.username, this.email, this.password, this.userTodo});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    email = json['email'];
    password = json['password'];
    if (json['user_todo'] != null) {
      userTodo = <UserTodo>[];
      json['user_todo'].forEach((v) {
        userTodo!.add(new UserTodo.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['username'] = this.username;
    data['email'] = this.email;
    data['password'] = this.password;
    if (this.userTodo != null) {
      data['user_todo'] = this.userTodo!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class UserTodo {
  int? id;
  String? title;
  String? desc;
  int? owner;

  UserTodo({this.id, this.title, this.desc, this.owner});

  UserTodo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    desc = json['desc'];
    owner = json['owner'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['desc'] = this.desc;
    data['owner'] = this.owner;
    return data;
  }
}
